# WEB SCRAPPING

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
ws=pd.read_html(r"https://en.wikipedia.org/wiki/List_of_territorial_entities_where_English_is_an_official_language")

In [3]:
ws

[   Nr         Country Alpha-3 code                 Region  Population  \
 0   1       Australia          AUS                Oceania    25019600
 1   2  New Zealand[1]          NZL                Oceania     4893830
 2   3  United Kingdom          GBR                 Europe    66040229
 3   4   United States          USA  North America/Oceania   328239523

   Primary language?
 0               Yes
 1               Yes
 2               Yes
 3               Yes  ,
     Nr                               Country Alpha-3 code  \
 0    1                Antigua and Barbuda[2]          ATG
 1    2                            Bahamas[2]          BHS
 2    3                           Barbados[3]          BRB
 3    4                             Belize[4]          BLZ
 4    5                           Botswana[4]          BWA
 5    6                            Burundi[5]          BDI
 6    7                           Cameroon[2]          CMR
 7    8                             Canada[2]          CAN
 8    9                     Cook Islands[2]14          COK
 9   10                           Dominica[2]          DMA
 10  11                           Eswatini[2]          SWZ
 11  12                               Fiji[2]          FJI
 12  13                             Gambia[2]          GMB
 13  14                              Ghana[2]          GHA
 14  15                            Grenada[2]          GRD
 15  16                             Guyana[6]          GUY
 16  17                           India[4][7]          IND
 17  18                         Ireland[8][9]          IRL
 18  19                           Jamaica[10]          JAM
 19  20                              Kenya[2]          KEN
 20  21                           Kiribati[2]          KIR
 21  22                            Lesotho[2]          LSO
 22  23                            Liberia[2]          LBR
 23  24                            Malawi[11]          MWI
 24  25                              Malta[2]          MLT
 25  26                   Marshall Islands[2]          MHL
 26  27                          Mauritius[2]          MUS
 27  28                         Micronesia[2]          FSM
 28  29                            Namibia[2]          NAM
 29  30                             Nauru[12]          NRU
 30  31                        Nigeria[2][13]          NGA
 31  32                             Niue[2]14          NIU
 32  33                           Pakistan[2]          PAK
 33  34                              Palau[4]          PLW
 34  35              Papua New Guinea[14][15]          PNG
 35  36                  Philippines[2][16]17          PHL
 36  37                             Rwanda[2]          RWA
 37  38             Saint Kitts and Nevis[17]          KNA
 38  39                        Saint Lucia[2]          LCA
 39  40  Saint Vincent and the Grenadines[18]          VCT
 40  41                             Samoa[19]          WSM
 41  42                         Seychelles[2]          SYC
 42  43                       Sierra Leone[2]          SLE
 43  44                         Singapore[20]          SGP
 44  45                    Solomon Islands[2]          SLB
 45  46                      South Africa[22]          ZAF
 46  47                       South Sudan[23]          SSD
 47  48                              Sudan[2]          SDN
 48  49                           Tanzania[2]          TZA
 49  50                             Tonga[24]          TON
 50  51                Trinidad and Tobago[2]          TTO
 51  52                             Tuvalu[4]          TUV
 52  53                             Uganda[2]          UGA
 53  54                           Vanuatu[26]          VUT
 54  55                             Zambia[2]          ZMB
 55  56                           Zimbabwe[2]          ZWE

                    Region    Population1  \
 0               Caribbean          85000
 1               Caribbean         331000
 2               Caribbean         294000
 3         Central America         288000
 4                  Africa        1882000
 5                  Africa       10114505
 6                  Africa       22534532
 7           North America       35985751
 8                 Oceania          20000
 9               Caribbean          73000
 10                 Africa        1141000
 11                Oceania         828000
 12                 Africa        1709000
 13                 Africa       27000000
 14              Caribbean         111000
 15          South America         738000
 16                   Asia     1247540000
 17                 Europe        4900000
 18              Caribbean        2714000
 19                 Africa       45010056
 20                Oceania          95000
 21                 Africa        2008000
 22                 Africa        3750000
 23                 Africa       16407000
 24                 Europe         430000
 25                Oceania          59000
 26  Africa / Indian Ocean        1262000
 27                Oceania         110000
 28                 Africa        2074000
 29                Oceania          10000
 30                 Africa      182202000
 31                Oceania           1600
 32                   Asia      212742631
 33                Oceania          20000
 34                Oceania        7059653
 35                   Asia      102885100
 36                 Africa       11262564
 37              Caribbean          50000
 38              Caribbean         165000
 39              Caribbean         120000
 40                Oceania         188000
 41  Africa / Indian Ocean          87000
 42                 Africa        6190280
 43                   Asia  5,469,700[21]
 44                Oceania         507000
 45                 Africa       54956900
 46                 Africa       12340000
 47                 Africa       40235000
 48                 Africa       51820000
 49                Oceania         100000
 50              Caribbean        1333000
 51                Oceania          11000
 52                 Africa       37873253
 53                Oceania         226000
 54                 Africa       16212000
 55                 Africa       13061239

                                     Primary language?
 0                                                 Yes
 1                                                 Yes
 2                                                 Yes
 3                                                 Yes
 4                                                  No
 5                                                  No
 6                                                  No
 7   Yes (except Quebec, northern New Brunswick and...
 8                                                 Yes
 9                                                 Yes
 10                                                 No
 11  Yes (used as lingua franca, mostly and widely ...
 12                                                 No
 13                        Yes (used as lingua franca)
 14    Yes (except for small French Creole population)
 15                                                Yes
 16                  No (but official and educational)
 17                         Yes (Irish is co-official)
 18                                                Yes
 19                    Yes (in business and education)
 20                                                 No
 21                                                 No
 22                                                Yes
 23                                                 No
 24      No (but official and in business / education)
 25                                                 No
 26                                                 No
 27                                                 No
 28                         No (used as lingua franca)
 29                             No (but widely spoken)
 30                        Yes (used as lingua franca)
 31                                                 No
 32                  No (but official and educational)
 33                                                 No
 34                                                Yes
 35                    Yes (co-official with Filipino)
 36                  No (but official and educational)
 37                                                Yes
 38                                                Yes
 39                                                Yes
 40                                                 No
 41                                                 No
 42                                                Yes
 43  Yes (used as lingua franca, mostly and widely ...
 44                                                 No
 45  No (but official, educational and lingua franc...
 46                                                 No
 47                                                 No
 48                                                 No
 49                                                 No
 50                                                Yes
 51                                                 No
 52              No (but official and educational)[25]
 53                                                 No
 54                                                 No
 55                         No (used as lingua franca)  ,
     Nr                   Country                      Region  Population1
 0    1           Bahrain[27][28]          Asia / Middle East      1378000
 1    2            Bangladesh[29]                        Asia    150039000
 2    3            Brunei[30][31]                        Asia       415717
 3    4              Cambodia[32]                        Asia     15288489
 4    5                Cyprus[33]  Europe, Asia / Middle East      1141166
 5    6                Eritrea[2]                      Africa      6234000
 6    7               Ethiopia[2]                      Africa     85000000
 7    8        Israel[34][35][36]          Asia / Middle East      8051200
 8    9                Jordan[37]          Asia / Middle East      9882401
 9   10                Kuwait[38]          Asia / Middle East      4348395
 10  11              Malaysia[39]                        Asia     30018242
 11  12              Maldives[40]                        Asia       427756
 12  13               Myanmar[41]                        Asia     51486253
 13  14                  Oman[42]          Asia / Middle East      4424762
 14  15                 Qatar[43]          Asia / Middle East      2675522
 15  16         Sri Lanka[44][45]                        Asia     20277597
 16  17  United Arab Emirates[46]          Asia / Middle East      5779760,
                          Entity          Region  Population1  \
 0         Akrotiri and Dhekelia          Europe      15700.0
 1              American Samoa11         Oceania      67700.0
 2                   Anguilla[2]       Caribbean      13101.0
 3                   Bermuda9[2]   North America      65000.0
 4     British Virgin Islands[2]       Caribbean      23000.0
 5             Cayman Islands[4]       Caribbean      47000.0
 6                   Curaçao[47]       Caribbean     150563.0
 7              Falkland Islands  South Atlantic       3000.0
 8                  Gibraltar[2]          Europe      33000.0
 9                         Guam4         Oceania     173000.0
 10                Hong Kong2[2]            Asia    7097600.0
 11                 Isle of Man8          Europe      80058.0
 12                   Jersey6[2]          Europe      89300.0
 13            Norfolk Island[2]       Australia       1828.0
 14    Northern Mariana Islands7         Oceania      53883.0
 15        Pitcairn Islands13[2]         Oceania         50.0
 16                 Puerto Rico3       Caribbean    3991000.0
 17                       Rotuma         Oceania          NaN
 18             Sint Maarten[48]       Caribbean      40900.0
 19  Turks and Caicos Islands[2]       Caribbean      26000.0
 20         U.S. Virgin Islands5       Caribbean     111000.0

                                     Primary language?
 0                                                  No
 1                             Yes (Along with Samoan)
 2                                                 Yes
 3                                                 Yes
 4                                                 Yes
 5                                                 Yes
 6                                                  No
 7                                                 Yes
 8                                                 Yes
 9                                                 Yes
 10      No (But de facto co-official with Cantonese )
 11                                                Yes
 12                                                Yes
 13                                                Yes
 14                                                 No
 15                                                Yes
 16  No (Co-official with Spanish as the primary la...
 17                                                 No
 18                                                Yes
 19                                                Yes
 20                                                Yes  ,
                                             Entity          Region  \
 0                   British Indian Ocean Territory    Indian Ocean
 1                                       Guernsey10          Europe
 2                                    Montserrat[2]       Caribbean
 3  Saint Helena, Ascension and Tristan da Cunha[4]  South Atlantic

    Population1
 0         3000
 1        61811
 2         5900
 3         5660  ,
                          Entity     Region  Population1
 0         Christmas Island12[2]  Australia         1508
 1  Cocos (Keeling) Islands16[2]  Australia          596
 2                   Tokelau[49]    Oceania         1400,
                      Subdivision         Country         Region  Population
 0                    Alabama[50]   United States  North America     4833722
 1                     Alaska[51]   United States  North America      735132
 2                    Arizona[52]   United States  North America     6626624
 3                   Arkansas[50]   United States  North America     2959373
 4                 California[50]   United States  North America    38332521
 5                   Colorado[50]   United States  North America     5268367
 6                    Florida[50]   United States  North America    21299325
 7                    Georgia[50]   United States  North America    10519475
 8                     Hawaii[50]   United States        Oceania     1404054
 9                      Idaho[50]   United States  North America     1612136
 10                  Illinois[50]   United States  North America    12882135
 11                   Indiana[50]   United States  North America     6570902
 12                      Iowa[50]   United States  North America     3090416
 13                    Kansas[50]   United States  North America     2893957
 14                  Kentucky[50]   United States  North America     4395295
 15             Massachusetts[53]   United States  North America     6794422
 16               Mississippi[50]   United States  North America     2991207
 17                  Missouri[50]   United States  North America     6083672
 18                   Montana[50]   United States  North America     1015165
 19                  Nebraska[50]   United States  North America     1868516
 20             New Hampshire[50]   United States  North America     1323459
 21            North Carolina[50]   United States  North America     9848060
 22              North Dakota[50]   United States  North America      723393
 23          Northern Ireland[54]  United Kingdom         Europe     1876695
 24                  Oklahoma[55]   United States  North America     3850568
 25                      Saba[56]     Netherlands      Caribbean        1991
 26  San Andrés y Providencia[57]        Colombia  South America       75167
 27           Sarawak[58][59][60]        Malaysia           Asia     2471140
 28                  Scotland[61]  United Kingdom         Europe     5424800
 29            Sint Eustatius[56]     Netherlands      Caribbean        3897
 30            South Carolina[50]   United States  North America     4774839
 31              South Dakota[50]   United States  North America      844877
 32                 Tennessee[50]   United States  North America     6495978
 33                      Utah[50]   United States  North America     2900872
 34                  Virginia[50]   United States  North America     8260405
 35                     Wales[62]  United Kingdom         Europe     3125000
 36             West Virginia[63]   United States  North America     1844128
 37                   Wyoming[50]   United States  North America      582658,
                      vteCountries and languages lists  \
 0   CountriesBy languagesSpoken Countries by spoke...
 1                                           Countries
 2   By languagesSpoken Countries by spoken languag...
 3                                        By languages
 4                                              Spoken
 5                                            Official
 6                                            Endonyms
 7                                             Exonyms
 8   LanguagesBy continent Africa Americas North So...
 9                                           Languages
 10  By continent Africa Americas North South Asia ...
 11                                       By continent
 12                                         By country
 13                                      By population
 14                                          By family
 15            Language-basedgeopoliticalorganizations
 16                                           See also

                    vteCountries and languages lists.1
 0   CountriesBy languagesSpoken Countries by spoke...
 1                                           Countries
 2   By languagesSpoken Countries by spoken languag...
 3   Spoken Countries by spoken languages Official ...
 4                       Countries by spoken languages
 5   Countries by the number of recognized official...
 6          Countries and capitals in native languages
 7   Country names in various languages A–C D–I J–P...
 8   LanguagesBy continent Africa Americas North So...
 9                                           Languages
 10  By continent Africa Americas North South Asia ...
 11  Africa Americas North South Asia East South Eu...
 12  Official languages by state List of languages ...
 13  By number of native speakers By number of tota...
 14  Language families List of Afro-Asiatic languag...
 15  Arab League (Arabic) Dutch Language Union (Dut...
 16              Lists of languages Category:Languages  ,
                                            Countries  \
 0  By languagesSpoken Countries by spoken languag...
 1                                       By languages
 2                                             Spoken
 3                                           Official
 4                                           Endonyms
 5                                            Exonyms

                                          Countries.1
 0  By languagesSpoken Countries by spoken languag...
 1  Spoken Countries by spoken languages Official ...
 2                      Countries by spoken languages
 3  Countries by the number of recognized official...
 4         Countries and capitals in native languages
 5  Country names in various languages A–C D–I J–P...  ,
               0                                                  1
 0  By languages  Spoken Countries by spoken languages Official ...
 1        Spoken                      Countries by spoken languages
 2      Official  Countries by the number of recognized official...

In [4]:
country1=ws[0] #for 1st table

In [5]:
country1

,Nr,Country,Alpha-3 code,Region,Population,Primary language?
0,1,Australia,AUS,Oceania,25019600,Yes
1,2,New Zealand[1],NZL,Oceania,4893830,Yes
2,3,United Kingdom,GBR,Europe,66040229,Yes
3,4,United States,USA,North America/Oceania,328239523,Yes

In [6]:
country2=ws[1]

In [7]:
country2

,Nr,Country,Alpha-3 code,Region,Population1,Primary language?
0,1,Antigua and Barbuda[2],ATG,Caribbean,85000,Yes
1,2,Bahamas[2],BHS,Caribbean,331000,Yes
2,3,Barbados[3],BRB,Caribbean,294000,Yes
3,4,Belize[4],BLZ,Central America,288000,Yes
4,5,Botswana[4],BWA,Africa,1882000,No
5,6,Burundi[5],BDI,Africa,10114505,No
6,7,Cameroon[2],CMR,Africa,22534532,No
7,8,Canada[2],CAN,North America,35985751,"Yes (except Quebec, northern New Brunswick and..."
8,9,Cook Islands[2]14,COK,Oceania,20000,Yes
9,10,Dominica[2],DMA,Caribbean,73000,Yes
10,11,Eswatini[2],SWZ,Africa,1141000,No
11,12,Fiji[2],FJI,Oceania,828000,"Yes (used as lingua franca, mostly and widely ..."
12,13,Gambia[2],GMB,Africa,1709000,No
13,14,Ghana[2],GHA,Africa,27000000,Yes (used as lingua franca)
14,15,Grenada[2],GRD,Caribbean,111000,Yes (except for small French Creole population)
15,16,Guyana[6],GUY,South America,738000,Yes
16,17,India[4][7],IND,Asia,1247540000,No (but official and educational)
17,18,Ireland[8][9],IRL,Europe,4900000,Yes (Irish is co-official)
18,19,Jamaica[10],JAM,Caribbean,2714000,Yes
19,20,Kenya[2],KEN,Africa,45010056,Yes (in business and education)
20,21,Kiribati[2],KIR,Oceania,95000,No
21,22,Lesotho[2],LSO,Africa,2008000,No
22,23,Liberia[2],LBR,Africa,3750000,Yes
23,24,Malawi[11],MWI,Africa,16407000,No
24,25,Malta[2],MLT,Europe,430000,No (but official and in business / education)
25,26,Marshall Islands[2],MHL,Oceania,59000,No
26,27,Mauritius[2],MUS,Africa / Indian Ocean,1262000,No
27,28,Micronesia[2],FSM,Oceania,110000,No
28,29,Namibia[2],NAM,Africa,2074000,No (used as lingua franca)
29,30,Nauru[12],NRU,Oceania,10000,No (but widely spoken)
30,31,Nigeria[2][13],NGA,Africa,182202000,Yes (used as lingua franca)
31,32,Niue[2]14,NIU,Oceania,1600,No
32,33,Pakistan[2],PAK,Asia,212742631,No (but official and educational)
33,34,Palau[4],PLW,Oceania,20000,No
34,35,Papua New Guinea[14][15],PNG,Oceania,7059653,Yes
35,36,Philippines[2][16]17,PHL,Asia,102885100,Yes (co-official with Filipino)
36,37,Rwanda[2],RWA,Africa,11262564,No (but official and educational)
37,38,Saint Kitts and Nevis[17],KNA,Caribbean,50000,Yes
38,39,Saint Lucia[2],LCA,Caribbean,165000,Yes
39,40,Saint Vincent and the Grenadines[18],VCT,Caribbean,120000,Yes
40,41,Samoa[19],WSM,Oceania,188000,No
41,42,Seychelles[2],SYC,Africa / Indian Ocean,87000,No
42,43,Sierra Leone[2],SLE,Africa,6190280,Yes
43,44,Singapore[20],SGP,Asia,"5,469,700[21]","Yes (used as lingua franca, mostly and widely ..."
44,45,Solomon Islands[2],SLB,Oceania,507000,No
45,46,South Africa[22],ZAF,Africa,54956900,"No (but official, educational and lingua franc..."
46,47,South Sudan[23],SSD,Africa,12340000,No
47,48,Sudan[2],SDN,Africa,40235000,No
48,49,Tanzania[2],TZA,Africa,51820000,No
49,50,Tonga[24],TON,Oceania,100000,No
50,51,Trinidad and Tobago[2],TTO,Caribbean,1333000,Yes
51,52,Tuvalu[4],TUV,Oceania,11000,No
52,53,Uganda[2],UGA,Africa,37873253,No (but official and educational)[25]
53,54,Vanuatu[26],VUT,Oceania,226000,No
54,55,Zambia[2],ZMB,Africa,16212000,No
55,56,Zimbabwe[2],ZWE,Africa,13061239,No (used as lingua franca)

In [8]:
country1=country1.loc[:,["Alpha-3 code","Primary language?"]]

In [9]:
country1

  Alpha-3 code Primary language?
0          AUS               Yes
1          NZL               Yes
2          GBR               Yes
3          USA               Yes

In [10]:
country2=country2.loc[:,["Alpha-3 code","Primary language?"]]

In [11]:
country2

   Alpha-3 code                                  Primary language?
0           ATG                                                Yes
1           BHS                                                Yes
2           BRB                                                Yes
3           BLZ                                                Yes
4           BWA                                                 No
5           BDI                                                 No
6           CMR                                                 No
7           CAN  Yes (except Quebec, northern New Brunswick and...
8           COK                                                Yes
9           DMA                                                Yes
10          SWZ                                                 No
11          FJI  Yes (used as lingua franca, mostly and widely ...
12          GMB                                                 No
13          GHA                        Yes (used as lingua franca)
14          GRD    Yes (except for small French Creole population)
15          GUY                                                Yes
16          IND                  No (but official and educational)
17          IRL                         Yes (Irish is co-official)
18          JAM                                                Yes
19          KEN                    Yes (in business and education)
20          KIR                                                 No
21          LSO                                                 No
22          LBR                                                Yes
23          MWI                                                 No
24          MLT      No (but official and in business / education)
25          MHL                                                 No
26          MUS                                                 No
27          FSM                                                 No
28          NAM                         No (used as lingua franca)
29          NRU                             No (but widely spoken)
30          NGA                        Yes (used as lingua franca)
31          NIU                                                 No
32          PAK                  No (but official and educational)
33          PLW                                                 No
34          PNG                                                Yes
35          PHL                    Yes (co-official with Filipino)
36          RWA                  No (but official and educational)
37          KNA                                                Yes
38          LCA                                                Yes
39          VCT                                                Yes
40          WSM                                                 No
41          SYC                                                 No
42          SLE                                                Yes
43          SGP  Yes (used as lingua franca, mostly and widely ...
44          SLB                                                 No
45          ZAF  No (but official, educational and lingua franc...
46          SSD                                                 No
47          SDN                                                 No
48          TZA                                                 No
49          TON                                                 No
50          TTO                                                Yes
51          TUV                                                 No
52          UGA              No (but official and educational)[25]
53          VUT                                                 No
54          ZMB                                                 No
55          ZWE                         No (used as lingua franca)

Concatenating the countries

In [12]:
master=pd.concat([country1,country2])

In [13]:
master.head()

  Alpha-3 code Primary language?
0          AUS               Yes
1          NZL               Yes
2          GBR               Yes
3          USA               Yes
0          ATG               Yes

In [14]:
master.reset_index(drop='index',inplace=True)

In [15]:
master.head()

  Alpha-3 code Primary language?
0          AUS               Yes
1          NZL               Yes
2          GBR               Yes
3          USA               Yes
4          ATG               Yes

Renaming the Columns

In [16]:
master.rename(columns={"Alpha-3 code":"country_code","Primary language?":"Official_lang"},inplace=True)

In [17]:
master["Official_lang"]=master["Official_lang"].apply(lambda x:x.split()[0])

In [18]:
master.head(2)

  country_code Official_lang
0          AUS           Yes
1          NZL           Yes

Converting to csv file

In [19]:
master.to_csv('english_countries.csv',index=False)

In [20]:
english_countries=pd.read_csv('english_countries.csv')

In [21]:
english_countries.head()

  country_code Official_lang
0          AUS           Yes
1          NZL           Yes
2          GBR           Yes
3          USA           Yes
4          ATG           Yes